export const DATA = [
    {
        id:   1,
    name: "Title 1",
        img: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
        date: "21.07.2021",
        author: "Baltac Mihai-Cristian",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.Sed ipsum quam, molestie ut dignissim nec, elementum ultrices turpis. Nunc quis vestibulum mi. Cras scelerisque luctus aliquam. Vivamus quis maximus urna. Sed massa elit, iaculis sed efficitur eget, ornare porta enim. Phasellus eleifend facilisis faucibus. Donec at metus at odio semper molestie eu vitae arcu. Suspendisse sit amet hendrerit dolor. Pellentesque sit amet quam quis mauris feugiat ornare in eget justo. Nunc molestie, tortor vitae elementum lacinia, dolor purus elementum ante, condimentum convallis lectus neque sit amet arcu. Vestibulum accumsan viverra dictum. Sed tempor ultricies odio, non viverra ligula mattis quis.In sed neque neque. Integer dui nisl, ultricies sed leo ut, pretium pellentesque eros. Nunc eu gravida nunc, a tempus nulla. Maecenas vulputate sem at urna mattis, et dignissim libero lobortis. Donec condimentum turpis nibh, vel aliquet ligula vehicula et. Nam dapibus congue elit ut rhoncus. Quisque pulvinar maximus risus. Ut ex eros, maximus eu euismod eu, tincidunt ut turpis.Ut ac ante quis metus tincidunt sodales id at lacus. Etiam vitae faucibus lectus, quis scelerisque ex. Morbi iaculis nunc nec urna ullamcorper, a lobortis magna pharetra. Nulla cursus viverra erat sed laoreet. Suspendisse vel nisl eget ante finibus egestas. Sed pharetra tincidunt scelerisque. Aliquam non molestie dolor. Duis porttitor nunc a massa consequat, in faucibus purus gravida. Vivamus suscipit ligula at magna condimentum efficitur. Nullam sit amet ex sit amet ligula aliquam dictum."

    },
    {
        id:   2,
        name: "Title 2",
        img: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
        date: "21.07.2021",
        author: "Baltac Mihai-Cristian",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.Sed ipsum quam, molestie ut dignissim nec, elementum ultrices turpis. Nunc quis vestibulum mi. Cras scelerisque luctus aliquam. Vivamus quis maximus urna. Sed massa elit, iaculis sed efficitur eget, ornare porta enim. Phasellus eleifend facilisis faucibus. Donec at metus at odio semper molestie eu vitae arcu. Suspendisse sit amet hendrerit dolor. Pellentesque sit amet quam quis mauris feugiat ornare in eget justo. Nunc molestie, tortor vitae elementum lacinia, dolor purus elementum ante, condimentum convallis lectus neque sit amet arcu. Vestibulum accumsan viverra dictum. Sed tempor ultricies odio, non viverra ligula mattis quis.In sed neque neque. Integer dui nisl, ultricies sed leo ut, pretium pellentesque eros. Nunc eu gravida nunc, a tempus nulla. Maecenas vulputate sem at urna mattis, et dignissim libero lobortis. Donec condimentum turpis nibh, vel aliquet ligula vehicula et. Nam dapibus congue elit ut rhoncus. Quisque pulvinar maximus risus. Ut ex eros, maximus eu euismod eu, tincidunt ut turpis.Ut ac ante quis metus tincidunt sodales id at lacus. Etiam vitae faucibus lectus, quis scelerisque ex. Morbi iaculis nunc nec urna ullamcorper, a lobortis magna pharetra. Nulla cursus viverra erat sed laoreet. Suspendisse vel nisl eget ante finibus egestas. Sed pharetra tincidunt scelerisque. Aliquam non molestie dolor. Duis porttitor nunc a massa consequat, in faucibus purus gravida. Vivamus suscipit ligula at magna condimentum efficitur. Nullam sit amet ex sit amet ligula aliquam dictum."

    },{
        id:   3,
        name: "Title 3",
        img: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
        date: "21.07.2021",
        author: "Baltac Mihai-Cristian",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.Sed ipsum quam, molestie ut dignissim nec, elementum ultrices turpis. Nunc quis vestibulum mi. Cras scelerisque luctus aliquam. Vivamus quis maximus urna. Sed massa elit, iaculis sed efficitur eget, ornare porta enim. Phasellus eleifend facilisis faucibus. Donec at metus at odio semper molestie eu vitae arcu. Suspendisse sit amet hendrerit dolor. Pellentesque sit amet quam quis mauris feugiat ornare in eget justo. Nunc molestie, tortor vitae elementum lacinia, dolor purus elementum ante, condimentum convallis lectus neque sit amet arcu. Vestibulum accumsan viverra dictum. Sed tempor ultricies odio, non viverra ligula mattis quis.In sed neque neque. Integer dui nisl, ultricies sed leo ut, pretium pellentesque eros. Nunc eu gravida nunc, a tempus nulla. Maecenas vulputate sem at urna mattis, et dignissim libero lobortis. Donec condimentum turpis nibh, vel aliquet ligula vehicula et. Nam dapibus congue elit ut rhoncus. Quisque pulvinar maximus risus. Ut ex eros, maximus eu euismod eu, tincidunt ut turpis.Ut ac ante quis metus tincidunt sodales id at lacus. Etiam vitae faucibus lectus, quis scelerisque ex. Morbi iaculis nunc nec urna ullamcorper, a lobortis magna pharetra. Nulla cursus viverra erat sed laoreet. Suspendisse vel nisl eget ante finibus egestas. Sed pharetra tincidunt scelerisque. Aliquam non molestie dolor. Duis porttitor nunc a massa consequat, in faucibus purus gravida. Vivamus suscipit ligula at magna condimentum efficitur. Nullam sit amet ex sit amet ligula aliquam dictum."

    },{
        id:   4,
        name: "Title 4",
        img: "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg",
        date: "21.07.2021",
        author: "Baltac Mihai-Cristian",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.Sed ipsum quam, molestie ut dignissim nec, elementum ultrices turpis. Nunc quis vestibulum mi. Cras scelerisque luctus aliquam. Vivamus quis maximus urna. Sed massa elit, iaculis sed efficitur eget, ornare porta enim. Phasellus eleifend facilisis faucibus. Donec at metus at odio semper molestie eu vitae arcu. Suspendisse sit amet hendrerit dolor. Pellentesque sit amet quam quis mauris feugiat ornare in eget justo. Nunc molestie, tortor vitae elementum lacinia, dolor purus elementum ante, condimentum convallis lectus neque sit amet arcu. Vestibulum accumsan viverra dictum. Sed tempor ultricies odio, non viverra ligula mattis quis.In sed neque neque. Integer dui nisl, ultricies sed leo ut, pretium pellentesque eros. Nunc eu gravida nunc, a tempus nulla. Maecenas vulputate sem at urna mattis, et dignissim libero lobortis. Donec condimentum turpis nibh, vel aliquet ligula vehicula et. Nam dapibus congue elit ut rhoncus. Quisque pulvinar maximus risus. Ut ex eros, maximus eu euismod eu, tincidunt ut turpis.Ut ac ante quis metus tincidunt sodales id at lacus. Etiam vitae faucibus lectus, quis scelerisque ex. Morbi iaculis nunc nec urna ullamcorper, a lobortis magna pharetra. Nulla cursus viverra erat sed laoreet. Suspendisse vel nisl eget ante finibus egestas. Sed pharetra tincidunt scelerisque. Aliquam non molestie dolor. Duis porttitor nunc a massa consequat, in faucibus purus gravida. Vivamus suscipit ligula at magna condimentum efficitur. Nullam sit amet ex sit amet ligula aliquam dictum."

    },{
        id:   5,
        name: "Title 5",
        img: "https://mymodernmet.com/wp/wp-content/uploads/2019/07/will-burrard-lucas-beetlecam-23-1024x683.jpg",
        date: "21.07.2021",
        author: "Baltac Mihai-Cristian",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas id rhoncus enim, lacinia elementum nunc. Phasellus vitae augue tincidunt, gravida velit ut, bibendum urna. Morbi auctor hendrerit sagittis. Nam tincidunt massa at nulla iaculis malesuada. Phasellus malesuada ac quam ac ornare. Praesent sem velit, euismod non pretium ac, interdum eu est. Aenean vel purus sem. In in hendrerit ante. Nam laoreet eleifend velit, vulputate semper lectus porta ac. Sed congue porta nunc a pellentesque. Maecenas feugiat purus nec erat congue, vel molestie massa varius. Nullam ornare mattis enim, ullamcorper faucibus tortor iaculis in. Aliquam cursus sodales lorem sit amet consectetur.Sed ipsum quam, molestie ut dignissim nec, elementum ultrices turpis. Nunc quis vestibulum mi. Cras scelerisque luctus aliquam. Vivamus quis maximus urna. Sed massa elit, iaculis sed efficitur eget, ornare porta enim. Phasellus eleifend facilisis faucibus. Donec at metus at odio semper molestie eu vitae arcu. Suspendisse sit amet hendrerit dolor. Pellentesque sit amet quam quis mauris feugiat ornare in eget justo. Nunc molestie, tortor vitae elementum lacinia, dolor purus elementum ante, condimentum convallis lectus neque sit amet arcu. Vestibulum accumsan viverra dictum. Sed tempor ultricies odio, non viverra ligula mattis quis.In sed neque neque. Integer dui nisl, ultricies sed leo ut, pretium pellentesque eros. Nunc eu gravida nunc, a tempus nulla. Maecenas vulputate sem at urna mattis, et dignissim libero lobortis. Donec condimentum turpis nibh, vel aliquet ligula vehicula et. Nam dapibus congue elit ut rhoncus. Quisque pulvinar maximus risus. Ut ex eros, maximus eu euismod eu, tincidunt ut turpis.Ut ac ante quis metus tincidunt sodales id at lacus. Etiam vitae faucibus lectus, quis scelerisque ex. Morbi iaculis nunc nec urna ullamcorper, a lobortis magna pharetra. Nulla cursus viverra erat sed laoreet. Suspendisse vel nisl eget ante finibus egestas. Sed pharetra tincidunt scelerisque. Aliquam non molestie dolor. Duis porttitor nunc a massa consequat, in faucibus purus gravida. Vivamus suscipit ligula at magna condimentum efficitur. Nullam sit amet ex sit amet ligula aliquam dictum."

    }
]